### ISSUE TITLE
GameRound Input Bug in Game.cs

### ISSUE THREAD

**Issue by Zachari** [PonyoHuesers/.NET-BlackJack#1]
Currently, invalid input (all strings aside from 'S', 's', 'H', 'h') causes the current game to end regardless of the state. This issue is caused by the code block (starting on line 79 of Game.cs) below as a result of only checking for 'S' and 'H' before ending a round.

**Current Code:**
```c#
Console.Write("Stay or Hit? (Enter 'S' or 'H'): ");

var input = Console.ReadLine().ToUpper();

if (input == "S")
{
    if (dealer.didBustToSeventeen(dealer, deck) == true)
    {
        dealer.WonOrLossOutput("dealerBust", dealer);
        return 0;
    }
    else
    {
        var outcome = Game.CompareHands(player, dealer);
        dealer.WonOrLossOutput(outcome, dealer);                    
    }
        
}

if (input == "H")
{
    Console.Clear();
    deck.PlayerDraw(player);

    if(player.SumCardValues() > 21 && Ace.IsAceInHand(player))
    {
        Ace.ReplaceAceValue(player);
        GameRound(player, dealer, deck);
    }
    else
    {
        GameRound(player, dealer, deck);
    }
}

return 0;
```

As a result of this code, invalid code is accepted as valid, which causes an issue as both conditionals will be false. This leads to the process of comparing hands to output the result as well as GameRound being called to progress the game being skipped, and the game is immediately ended on the return statement.

A quick fix is to collect continue asking for proper input while the input is invalid. This solution does not account for the change to ConsoleKey and use of the ReadKey method instead of ReadLine that you discussed. It's meant to be an easy, quick fix with the least changes made to the code. Add this while loop below the initial input on line 80:

**Block to add:**
```c#
while (input != "H" && input != "S")
{
    Console.Write("\nSorry, that was an invalid option! Try again using 'S' or 'H'.\n");
    Console.Write("Stay or Hit? (Enter 'S' or 'H'): ");
    input = Console.ReadLine().ToUpper();
}
```

**Code With Fix:**
```c#
Console.Write("Stay or Hit? (Enter 'S' or 'H'): ");
var input = Console.ReadLine().ToUpper();

while (input != "H" && input != "S")
{
    Console.Write("\nSorry, that was an invalid option! Try again using 'S' or 'H'.\n");
    Console.Write("Stay or Hit? (Enter 'S' or 'H'): ");
    input = Console.ReadLine().ToUpper();
}

if (input == "S")
{
    if (dealer.didBustToSeventeen(dealer, deck) == true)
    {
        dealer.WonOrLossOutput("dealerBust", dealer);
        return 0;
    }
    else
    {
        var outcome = Game.CompareHands(player, dealer);
        dealer.WonOrLossOutput(outcome, dealer);
    }

}

if (input == "H")
{
    Console.Clear();
    deck.PlayerDraw(player);

    if (player.SumCardValues() > 21 && Ace.IsAceInHand(player))
    {
        Ace.ReplaceAceValue(player);
        GameRound(player, dealer, deck);
    }
    else
    {
        GameRound(player, dealer, deck);
    }
}

return 0;
```

However, I'd recommended that the switch to using a ConsoleKey explicitly and ReadKey be used for input. Explicit types allow for better, more predictable handling of the input for the developer. Using an explicit string type for 'input' would do the same without requiring any code changes. 

While the var keyword will implicitly do this, it's good practice to use it when dealing with anonymous types. In this case, it's not that big of a deal, and indeed, it is a matter of taste in the majority of cases. There is no noticeable efficiency or performance boost from using explicit types. However, this practice is helpful in noticing and avoiding issues where there may be a type conflict.

**Comment by PonyoHuesers** [comment]
Fantastic documentation. I have implemented and pushed your suggested changes. Thanks again!
